import Link from "next/link";
import { RequireRole } from "@/lib/auth/guards";
import { createClient } from "@/lib/supabase/server";
import { getEntitlementsForAuth } from "@/lib/billing/queries";
import { isFeatureUnlocked, pricingHrefForAccount } from "@/lib/billing/feature-access";

type FanlinkEvent = { event_type: string; platform: string | null };
type FanlinkRow = {
 id: string; title: string; artist_name: string; artist_slug: string; song_slug: string;
 resolution_status: string; preview_ready: boolean; platform_links: Record<string,string> | null;
 fanlink_events: FanlinkEvent[] | null;
};

export default async function FanlinksPage(){
 const ctx=await RequireRole(["artist","label"]); const entitlements=await getEntitlementsForAuth(ctx); if(!isFeatureUnlocked(entitlements,"fanlinks")) return <main className="space-y-6"><section className="rounded-[1.5rem] border border-[var(--nexo-border)] bg-[var(--nexo-card)] p-8"><p className="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-[var(--nexo-text-muted)]">Paid plan feature</p><h1 className="mt-2 text-3xl font-semibold">Fanlinks</h1><p className="mt-2 text-small text-[var(--nexo-text-secondary)]">Fanlinks, DSP click analytics and preview tools are not included on the free plan.</p><Link className="mt-5 inline-block rounded-full bg-[var(--nexo-text)] px-4 py-2 text-small font-semibold [color:var(--nexo-text-inverse)]" href={pricingHrefForAccount(entitlements.accountType)}>Upgrade plan</Link></section></main>; const db=await createClient();
 const {data}=await db.from("fanlinks").select("id,title,artist_name,artist_slug,song_slug,resolution_status,preview_ready,platform_links,fanlink_events(event_type,platform)").eq("owner_user_id",ctx.userId).order("updated_at",{ascending:false});
 const fanlinks=(data??[]) as FanlinkRow[];
 return <main className="space-y-6"><section className="rounded-[1.5rem] border border-[var(--nexo-border)] bg-[var(--nexo-card)] p-6 sm:p-8"><p className="text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-[var(--nexo-text-muted)]">Audience tools</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">Fanlinks</h1><p className="mt-2 max-w-2xl text-small text-[var(--nexo-text-secondary)]">Share one beautiful Nexo link for every live release, monitor store clicks and views, and see preview readiness.</p><div className="mt-5 flex flex-wrap gap-2"><Link href="/dashboard/releases" className="rounded-full bg-[var(--nexo-text)] px-4 py-2 text-small font-semibold [color:var(--nexo-text-inverse)]">View live releases</Link><Link href="/analytics/streams" className="rounded-full border border-[var(--nexo-border)] px-4 py-2 text-small font-semibold">View analytics</Link></div></section><div className="grid gap-4">{fanlinks.map((f)=>{const events=f.fanlink_events??[];const clicks=events.filter((e)=>e.event_type==="platform_click").length;return <article key={f.id} className="rounded-[1.25rem] border border-[var(--nexo-border)] bg-[var(--nexo-card)] p-5 shadow-[var(--nexo-shadow-sm)] transition-transform hover:-translate-y-0.5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{f.title}</h2><p className="text-caption text-[var(--nexo-text-muted)]">{f.artist_name}</p></div><span className="text-caption">{f.resolution_status}</span></div><div className="mt-3 flex flex-wrap gap-4 text-caption"><span>{Object.keys(f.platform_links??{}).length} stores</span><span>{clicks} DSP clicks</span><span>{events.filter((e)=>e.event_type==="view").length} views</span><span>{f.preview_ready?"30-sec preview ready":"Preview processing"}</span></div><div className="mt-4"><Link className="underline" href={"/"+f.artist_slug+"/"+f.song_slug} target="_blank">Open public Fanlink</Link></div></article>})}{!fanlinks.length?<p className="rounded-[var(--nexo-radius)] border border-[var(--nexo-border)] p-5 text-small">No live-release Fanlinks yet.</p>:null}</div></main>;
}