export const PORTAL_SERVICE_KINDS = [
  "ringtone",
  "mastering",
  "sync",
  "physical",
  "dsp_pitching",
  "campaign",
  "third_party_playlisting",
  "ad_box",
  "influencers",
  "labs",
  "luminate",
  "youtube_allowlist",
  "youtube_manual_claim",
  "tiktok_manual_claim",
  "soundcloud_allowlist",
  "meta_allowlist",
  "priority_pitch",
  "chart_registration",
  "audio_recognition",
  "tiktok_cml",
  "promotional_assets",
  "fan_blast",
  "ai_mastering",
  "award_monitoring",
  "greenlist",
  "blocklist",
  "profile_defender",
  "conflict_resolution",
] as const;

export type PortalServiceKind = (typeof PORTAL_SERVICE_KINDS)[number];

export function isPortalServiceKind(value: string): value is PortalServiceKind {
  return (PORTAL_SERVICE_KINDS as readonly string[]).includes(value);
}

/** Optional services shown on Enrollments. Unenrolled until a real row exists. */
export const ENROLLABLE_SERVICES = [
  { key: "playlist_pitching", label: "Playlist pitching" },
  { key: "nexo_labs", label: "Nexo Labs" },
  { key: "luminate", label: "Luminate registration" },
  { key: "sync", label: "Sync representation" },
  { key: "physical", label: "Physical distribution" },
  { key: "ad_box", label: "Nexo Ad Box" },
] as const;

export const SERVICE_KIND_LABEL: Record<PortalServiceKind, string> = {
  ringtone: "Create Ringtone",
  mastering: "Master Your Track",
  sync: "Sync Representation",
  physical: "Physical Distribution",
  dsp_pitching: "DSP Pitching",
  campaign: "Release Campaign Builder",
  third_party_playlisting: "Third Party Playlisting",
  ad_box: "Nexo Ad Box",
  influencers: "Influencers",
  labs: "Nexo Labs",
  luminate: "Luminate Registration",
  youtube_allowlist: "YouTube Allowlist",
  youtube_manual_claim: "YouTube Manual Claim",
  tiktok_manual_claim: "TikTok Manual Claim",
  soundcloud_allowlist: "SoundCloud Allowlist",
  meta_allowlist: "Meta Allowlist",
  priority_pitch: "Priority Pitch",
  chart_registration: "Chart Registration",
  audio_recognition: "Audio Recognition",
  tiktok_cml: "TikTok CML",
  promotional_assets: "Promotional Assets",
  fan_blast: "Fan Blast",
  ai_mastering: "AI Mastering",
  award_monitoring: "Award Monitoring",
  greenlist: "Greenlist",
  blocklist: "Blocklist",
  profile_defender: "Profile Defender",
  conflict_resolution: "Conflict Resolution",
};

export const ANALYTICS_KEYS = [
  "streams",
  "meta",
  "youtube_ugc",
  "tiktok",
  "streamsafe",
  "spotify_discovery",
  "spotify_engagement",
  "downloads",
  "sales_overview",
  "sales_releases",
  "sales_tracks",
  "sales_stores",
  "sales_artists",
  "sales_territories",
  "sales_monthly",
  "stream_rate",
  "analytics_overview",
  "by_platform",
  "by_release",
  "usage_discovery",
  "insights",
  "audience",
  "reports_overview",
  "reports_sales",
  "reports_catalog",
  "reports_payouts",
  "reports_release_links",
  "reports_additional",
  "reports_stream_data",
  "reports_raw_data",
] as const;

export type AnalyticsKey = (typeof ANALYTICS_KEYS)[number];

export function isAnalyticsKey(value: string): value is AnalyticsKey {
  return (ANALYTICS_KEYS as readonly string[]).includes(value);
}

/** DSP codes we match on ingested ledger / import rows. Never invent counts. */
export const ANALYTICS_DSP_MATCH: Record<AnalyticsKey, string[]> = {
  streams: ["spotify", "apple", "apple_music", "audiomack", "amazon", "deezer", "tidal", "pandora", "youtube"],
  meta: ["meta", "facebook", "instagram"],
  youtube_ugc: ["youtube_ugc", "youtube", "yt_ugc"],
  tiktok: ["tiktok"],
  streamsafe: ["streamsafe"],
  spotify_discovery: ["spotify_discovery"],
  spotify_engagement: ["spotify", "spotify_engagement"],
  downloads: ["download", "itunes", "amazon_download"],
  sales_overview: [],
  sales_releases: [],
  sales_tracks: [],
  sales_stores: [],
  sales_artists: [],
  sales_territories: [],
  sales_monthly: [],
  stream_rate: [],
  analytics_overview: [],
  by_platform: [],
  by_release: [],
  usage_discovery: [],
  insights: [],
  audience: [],
  reports_overview: [],
  reports_sales: [],
  reports_catalog: [],
  reports_payouts: [],
  reports_release_links: [],
  reports_additional: [],
  reports_stream_data: [],
  reports_raw_data: [],
};
